### ISSUE TITLE
Provide .md5 checksum of files of dynamic nginx zip files

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#2133] opened 2017-05-16 17:57 UTC
A user requested this over the help email account so that they could verify the integrity of their large file download.

**Comment by antgonza** [comment] 2017-05-16 18:26
This is an interesting question because for biom/fna, raw files, etc. is an on the fly download ... so not sure how this will happen ... any ideas?

**Comment by wasade** [comment] 2017-05-16 18:27
We compute once and store on the file system in proximity to the files being downloaded? On the fly is quite expensive

**Comment by antgonza** [comment] 2017-05-16 18:32
It's quite cheap to generate as nginx takes care of everything. Let's discuss during a future Qiita dev-meeting.

**Comment by antgonza** [comment] 2017-10-04 17:12
Let's check if nginx has something for this, cause if not ... 😢

**Comment by antgonza** [comment] 2020-07-16 15:03
Just realized that this is a duplicate of https://github.com/biocore/qiita/issues/2920; closing this one as the other one has an explanation of how it currently works.

**Closed by antgonza** 2020-07-16 15:03 UTC
