### ISSUE TITLE
Redbiom interface is slow to load

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2571] opened 2018-04-23 19:35 UTC
Following steps in #2569 , click on + symbol to show the desired artifact to retrieve the sample of interest:
At first click:
![image](https://user-images.githubusercontent.com/27017606/39147632-0d33db6e-46ef-11e8-9234-595be6cce9ef.png)

And nearly 30 min later the screen looks the same:
![image](https://user-images.githubusercontent.com/27017606/39149041-ba6aeebe-46f2-11e8-9a16-62625041d157.png)

**Comment by antgonza** [comment] 2018-04-23 19:38
Check URGENT email to the qiita-admin. Anyway, the issue here is: https://github.com/biocore/qiita/issues/2570. We are currently gonna fix via nginx. Closing as this is a duplicate of #2570.

**Closed by antgonza** 2018-04-23 19:38 UTC
Labels: bug, performance, redbiom
