### ISSUE TITLE
Unlinked files due to error, can't re-link them.

### ISSUE THREAD

**Issue by borax** [biocore/qiita#1475] opened 2015-09-16 00:54 UTC
I have two sequencing files (forward and reverse reads) and a barcode file for each (Study #10297). I attempted to link them, but only selected one barcode file. I got the following error: 

*Status: failed: Job PREPROCESS: Error Job results: ValueError(Failed to execute: split_libraries_fastq.py --store_demultiplexed_fastq -i /projects/qiita_data/raw_data/700_April2015V4_S1_L001_R1_001.fastq -b /projects/qiita_data/raw_data/700_barcode_April1.txt -m /projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_001_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_002_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_003_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_004_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_005_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_006_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_007_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_008_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_009_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_010_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_011_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_012_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_013_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_014_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_015_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_016_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_017_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_018_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_019_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_020_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_021_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_022_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_023_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_024_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_025_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_026_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_027_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_028_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_029_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_030_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_031_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_032_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_033_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_034_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_035_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_036_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_037_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_038_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_039_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_040_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_041_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_042_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_043_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_044_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_045_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_046_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_047_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_048_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_049_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_050_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_051_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_052_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_053_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_054_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_055_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_056_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_057_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_058_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_059_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_060_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_061_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_062_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_063_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_064_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_065_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_066_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_067_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_068_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_069_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_070_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_071_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_072_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_073_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_074_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_075_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_076_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_077_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_078_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_079_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_080_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_081_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_082_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_083_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_084_MMF.txt,/projects/qiita_data/working_dir/MMF_1031c88RgI/April2015V4_S1_L001_RX_085_MMF.txt -o /projects/qiita_data/working_dir/slq_out_1031_700_Aqrkm1 --barcode_type 8 --max_bad_run_length 3 --max_barcode_errors 1.5 --min_per_read_length_fraction 0.75 --phred_quality_threshold 3 --sequence_max_n 0 stdout: stderr: Usage: split_libraries_fastq.py [options] {-i/--sequence_read_fps SEQUENCE_READ_FPS -o/--output_dir OUTPUT_DIR} [] indicates optional input (order unimportant) {} indicates required input (order unimportant) Example usage: Print help message and exit split_libraries_fastq.py -h Demultiplex and quality filter (at Phred >= Q20) one lane of Illumina fastq data and write results to ./slout_q20.: split_libraries_fastq.py -i lane1_read1.fastq.gz -b lane1_barcode.fastq.gz --rev_comp_mapping_barcodes -o slout_q20/ -m map.txt -q 19 Demultiplex and quality filter (at Phred >= Q20) one lane of Illumina fastq data and write results to ./slout_q20. Store trimmed quality scores in addition to sequence data.: split_libraries_fastq.py -i lane1_read1.fastq.gz -b lane1_barcode.fastq.gz --rev_comp_mapping_barcodes -o slout_q20/ -m map.txt --store_qual_scores -q 19 Demultiplex and quality filter (at Phred >= Q20) two lanes of Illumina fastq data and write results to ./slout_q20.: split_libraries_fastq.py -i lane1_read1.fastq.gz,lane2_read1.fastq.gz -b lane1_barcode.fastq.gz,lane2_barcode.fastq.gz --rev_comp_mapping_barcodes -o slout_q20/ -m map.txt,map.txt --store_qual_scores -q 19 Quality filter (at Phred >= Q20) one non-multiplexed lane of Illumina fastq data and write results to ./slout_single_sample_q20.: split_libraries_fastq.py -i lane1_read1.fastq.gz --sample_id my.sample.1 -o slout_single_sample_q20/ -q 19 --barcode_type 'not-barcoded' Quality filter (at Phred >= Q20) two non-multiplexed lanes of Illumina fastq data with different samples in each and write results to ./slout_not_multiplexed_q20.: split_libraries_fastq.py -i lane1_read1.fastq.gz,lane2_read1.fastq.gz --sample_id my.sample.1,my.sample.2 -o slout_not_multiplexed_q20/ -q 19 --barcode_type 'not-barcoded' split_libraries_fastq.py: error: Same number of sequence, barcode, and mapping files must be provided. ) Python output: None Standard output: Standard error: Job GEN_DEMUX_FILE: Error Job results: ImpossibleDependency() Python output: None Standard output: Standard error: Job INSERT_PREPROCESSED: Error Job results: ImpossibleDependency() Python output: None Standard output: Standard error:*

Oops. Looks like I need to link both barcode files? I unlinked all the files and when I went to re-link them the normal drop-down menus where I designate what type of file each file is were missing. Here's a picture:

![screen grab](https://cloud.githubusercontent.com/assets/4305894/9893900/6ba99a36-5bd2-11e5-8e7b-6d35b7eab32b.PNG)

I'm not sure how to proceed.

Thanks,

Zac

**Comment by josenavas** [comment] 2015-09-16 02:08
Hi @borax 

If you have forward and reverse reads you only need to link a single barcode files. However, I think the problem is in your prep template. If you have the column "run_prefix" it should have the same value for all the samples, as all the samples are in the same run, given that you only have a single set of forward/reverse/barcode file.

Regarding re-linking files, it looks like the screenshot that you sent is incomplete, since the dropdowns to choose the type of files should be on the right. Can you try to scroll to the right, in case that you don't see them?

Also, we have the help mail account `help.qiita@gmail.com`, which may be useful if you want to share your study information with us without making it public.

Hope this helps!

**Comment by borax** [comment] 2015-09-16 04:02
Sure enough the drop down menus were waaaaaay to the right! Sounds like something that might need to be tweaked in the web page design.

I also unified the "run_prefix" column across all samples. I am now getting an error about my mapping file (even though the sample and prep templates individually were both accepted), but I should be able to troubleshoot that with validate_mapping_file.py. 

What type of stuff should I post issues about on Github versus sending stuff to the gmail account, if you folks have a preference? I won't post anything here that I don't want public.

Zac

**Comment by josenavas** [comment] 2015-09-16 04:30
Interesting thing about the error in your mapping file, I would like to hear what is the specific problems that you're finding (we can discuss this over the help mail account).

Ideally, we would like that the issues in GitHub are more related with bugs in the system (e.g. the dropdown menus are waaaaay to the right) and/or functionality requests and improvements; while specific questions about your studies go to the help account. I just wanted to make sure that you also new the existence of the help account :smile:

**Comment by borax** [comment] 2015-09-16 18:14
After investigating the mapping file downloaded from QIITA, it looks like I have duplicate sample names. I had named the samples 1-85 in my templates, but now all sample names that are multiples of 10 are missing (10, 20, 30, etc.) and I have duplicate samples 1-8. Looks like the 0 at the end of these sample names was truncated off somewhere in the system, likely where the names are combined with the study number (for example sample 10297.10 is now an extra 10297.1). I double checked the  templates I uploaded, and the sample numbers were not truncated in my files (as Excel is notorious for doing) because they were not decimals there. Still, I wouldn't be surprised if this is my fault somehow.

Help?

**Comment by ackermag** [comment] 2015-09-16 19:41
I think it is an Excel thing  - it helps if you convert everything to test
in the Text Wizard or if you add an apostrophe character before the entry "
' ".
so:'10279.10 in the cell not 10279.10 which is assumed to be a decimal.

I can assist if my instructions are confusing.
Gail


On Wed, Sep 16, 2015 at 11:14 AM, Zachery Lewis <notifications@github.com>
wrote:

> After investigating the mapping file downloaded from QIITA, it looks like
> I have duplicate sample names. I had named the samples 1-85 in my
> templates, but now all sample names that are multiples of 10 are missing
> (10, 20, 30, etc.) and I have duplicate samples 1-8. Looks like the 0 at
> the end of these sample names was truncated off somewhere in the system,
> likely where the names are combined with the study number (for example
> sample 10297.10 is now an extra 10297.1). I double checked the templates I
> uploaded, and the sample numbers were not truncated in my files (as Excel
> is notorious for doing) because they were not decimals there. Still, I
> wouldn't be surprised if this is my fault somehow.
>
> Help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1475#issuecomment-140827439>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by antgonza** [comment] 2015-09-16 19:41
My guess is that the culprit is your friend Excel. Could you try downloading the file again and opening it in a text file editor? If it looks fine, could you make sure to open the file as text ... as @ackermag just suggested.

**Comment by josenavas** [comment] 2015-09-16 19:51
Just to support the comments from @antgonza and @ackermag 

I checked the system and the sample names that we have are the correct ones, both in the database and in the files, so the issue that you're seeing with duplicated samples are due to excel.

Which parameters are you using to preprocess your data?

**Comment by borax** [comment] 2015-09-16 21:51
This really seems like it *should* be an Excel thing. However, I opened the files I uploaded in Notepad++ (and gedit on a Linux machine just in case) and the sample numbers are perfect. No decimals, no truncated zeros. Just 1-85. I upload those template files to QIITA, redownload them after they are combined to the study number using a period (now 10279.10 instead of 10), open those files in Notepad++ and gedit and they are fine. It's not until I download the QIIME mapping file off of QIITA that I've noticed that they are truncated. I'm not sure how Excel could be influencing this, especially since they weren't ever decimal numbers before I uploaded them, and aren't truncated in the downloaded prep and sample template. It looks like it is the in the making of the mapping file that the error is introduced. I'm using barcode_type 8 and defaults to preprocess.

I can try giving them different sample names and see if that avoids the problem, but it would be nice to know definitively if it was my system or yours that's causing it.

**Comment by josenavas** [comment] 2015-09-16 21:59
Hi @borax ,

We just noticed that the mapping file used for preprocessing and the mapping file downloaded are not exactly the same. We detected the issue in there and we are going to work on fix it ASAP.

Sorry for any inconvenience and thanks for reporting the issue.

Thanks,

**Comment by borax** [comment] 2015-09-16 22:16
Great! Glad you found it! Hopefully it fixes the "Errors were found with mapping file, please run validate_mapping_file.py to identify problems" error I'm experiencing.

**Comment by josenavas** [comment] 2015-09-17 18:13
@borax I have a pull request in fixing the above mentioned issue.

Once the code is merged, we will schedule a system upgrade in the live system. Once it is updated, you will be able to process your data.

**Closed** 2015-09-18 13:01 UTC
