### ISSUE TITLE
Allowing collapsing the OTU table using collapse_sample.py 

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1279] opened 2015-06-19 18:41 UTC
The prep template can contain duplicate sample IDs since the same sample can be present in different runs.

![error1998](https://cloud.githubusercontent.com/assets/2501478/8260361/f59f70bc-1677-11e5-9e7e-cb925db7a34a.jpeg)

cc: @antgonza

**Comment by antgonza** [comment] 2015-06-19 18:43
If a sample has been sequenced N times, they should have N different names. Thus, IMOO not a bug.

**Comment by rob-knight** [comment] 2015-06-19 19:31
We have a separate field for biospecimen that would be the same, yes?

**Comment by antgonza** [comment] 2015-06-19 19:50
The user can add that column but is not a required field.

**Comment by josenavas** [comment] 2015-06-19 20:05
If we put them as 2 different samples, the processed OTU table will have these 2 samples and the user can download the table and collapse it, but we currently don't have a way of doing this.

**Comment by antgonza** [comment] 2015-06-19 20:11
@josenavas Do you mean that we do not have it in qiita? Cause in qiime we can use: collapse_samples.py. Either way, IMOO this can be a feature request which is not high priority.

**Comment by josenavas** [comment] 2015-06-19 20:13
Sorry, I was not specific. Yes, we don't have it in Qiita.
Just a note (we discussed offline, but I think it is important to put it here), studies like the Global Gut (in which the same set of samples was sequences multiple times) cannot be processed in Qiita in the way that we would process it using Qiime...

**Comment by josenavas** [comment] 2015-06-19 20:57
After discussing with @antgonza offline, it turns out that allowing merging the different runs is not correct, and you should do a pre-analysis before doing that. Thus, what needs to be allowed is to create a collapsed BIOM table (and hence a new mapping file) to perform other analysis.

**Comment by antgonza** [comment] 2019-01-24 20:56
This feature is now available via Qiime2; the current issue is that Qiime2 doesn't produce a matching mapping file and the validation fails in Qiita. Anyway, AFAIK there is a fix in the works in Q2. Thus, closing this issue.

**Closed by antgonza** 2019-01-24 20:56 UTC
Labels: enhancement
