### ISSUE TITLE
Test CLIs

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#120] opened 2014-06-19 20:58 UTC
Likely using whatever click suggests.

**Comment by RNAer** [comment] 2015-08-23 20:50
I am working on this. The plan is to write the tests in `qiita/scripts/test/`, but the problem is that there seems no easy way to import the command functions from `qiita/scripts/qiita` and `qiita/scripts/qiita-env`, unless we set `qiita/scripts` as a submodule instead. @ElDeveloper @antgonza @squirrelo @josenavas , do you have any ideas?

**Comment by josenavas** [comment] 2015-08-23 20:56
I don't think there is a big problem of setting it as a submodule. @ElDeveloper @antgonza ?

**Comment by antgonza** [comment] 2015-08-24 01:01
I think submodules is not a big deal but could you explain why this is the best option? BTW what about setting another job to test this https://travis-ci.org/biocore/qiita ...

**Comment by RNAer** [comment] 2015-08-24 02:55
another job is certainly an option, but isn't it nicer to take advantage of
click's testing facility and to avoid writing boiler plate code ourselves?
To do that, I have to do imports. I am not sure alternative way for that
besides submodules...

**Comment by antgonza** [comment] 2015-08-24 03:37
Good point! However, I'm not sure what's the import issue (looking at http://click.pocoo.org/3/testing/), could you give an example? Thanks.

**Comment by josenavas** [comment] 2015-08-24 03:41
What if we put the tests in the same file than the functions are? We will not have the imports problem

**Comment by RNAer** [comment] 2015-08-24 05:33
The click doc examples defines interface inside test function. that's why
no imports is needed. My example is here:
https://github.com/RNAer/qiita/blob/clitest/scripts/test/test_qiita.py

**Comment by antgonza** [comment] 2015-08-24 13:16
Got it, thanks! What about following @josenavas suggestion? Have tests within scripts?

**Comment by wasade** [comment] 2015-08-24 15:31
In the long since forgotten rewrite of split_libraries.py, what we did was
had the command line logic part of an API module. This worked extremely
well and easily testable. The script would just import the relevant
methods. The test harness would import the API methods cleanly since
they're already importable. This has the added advantage that the scripts
code becomes very tiny.

**Comment by wasade** [comment] 2015-08-24 15:38
Relevant links below:

[qiime](https://github.com/wasade/qiime/blob/wf_qual_filter_fasta/scripts/qiime), this is the actual "script"
[cli](https://github.com/wasade/qiime/blob/wf_qual_filter_fasta/qiime/cli.py)
[click_commands](https://github.com/wasade/qiime/blob/wf_qual_filter_fasta/qiime/click_commands.py)
[test_click_commands](https://github.com/wasade/qiime/blob/wf_qual_filter_fasta/tests/test_click_commands.py)

**Comment by josenavas** [comment] 2015-08-24 15:40
Thanks @wasade !

I really like that idea. @RNAer could you follow that approach?

**Comment by ElDeveloper** [comment] 2015-08-24 16:02
Yeah, that's the same thing we did for Platypus:
https://github.com/biocore/Platypus-Conquistador/blob/master/scripts/platypus

As a side note, a while ago I saw that Click's documentation suggests
that scripts be "deployed" in a different way compared to the approach
we are using:
http://click.pocoo.org/5/setuptools/#scripts-in-packages

**Comment by RNAer** [comment] 2015-08-25 02:22
@wasade , doesn't that still add an extra layer of code? You have a function doing real work, and then the click decorated cli, and another function in scripts dir call that cli. The last layer is not necessary if we make `scripts` a submodule.

**Comment by RNAer** [comment] 2015-08-25 02:30
What I had thought is essentially the same thing as described in the link that Yoshiki listed out.

**Comment by wasade** [comment] 2015-08-25 03:19
It may well add some extra code -- it was designed to fit into the existing
approach that qiime was doing

**Comment by antgonza** [comment] 2017-11-28 22:53
Closing as we are making the CLI qiita interaction bare minimum.

**Closed by antgonza** 2017-11-28 22:53 UTC
Labels: CLI, enhancement, testing
