### ISSUE TITLE
Cannot add samples to template with nan values on an integer column

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1226] opened 2015-06-01 22:09 UTC
@ackermag reported that when trying to add samples to an existing template, if there's an integer column say `AGE`, but the new samples do not have this value and the cell is set as `nan`, the upload will fail with this error:

```
Error running SQL query in queue EXTEND_SAMPLE_TEMPLATE_10145: INSERT INTO
qiita.sample_10145 (sample_id, title, anonymized_name, depth, common_name,
sample_type, taxon_id, altitude, description, assigned_from_geo, elevation,
env_biome, env_feature, env_matter, latitude, longitude,
collection_timestamp, country, area, extracted_dna_avail_now,
host_subject_id, has_physical_specimen, public, has_extracted_data,
required_sample_info_status, physical_specimen_location, slope_aspect,
approx_distance_transect_start_to_highest_tide_line_meters, weather, temp,
bearing_degrees, approx_distance_from_seawater_at_low_tide,
seawater_or_pore_water_ph, seawater_or_pore_water_ph_meth, sediment_ph,
sediment_ph_meth, seawater_or_pore_water_salinity,
seawater_or_pore_water_salinity_meth, sediment_salinity,
sediment_salinity_units, sediment_salinity_meth, moisture_content,
moisture_content_units, moisture_content_meth,
degree_of_saturation_percent, sand_grains_greater_than_355um_percent,
sand_grains_between_355_and_250um_percent,
sand_grains_between_250_and_106um_percent,
sand_grains_between_106_and_45um_percent,
sand_grains_less_than_45um_percent, sand_grain_method, nh4_n, nh4_n_units,
nh4_n_meth, no3_n, no3_n_units, no3_n_meth, po4_p, po4_p_units, po4_p_meth,
organic_matter_percent, organic_matter_meth, chlorophyll,
chlorophyll_units, chlorophyll_method, g_sand_or_ml_sw_for_dna_extraction,
dna_ext_method, physical_specimen_remaining, dna_extracted)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ARGS: ('10145.BLANK.2A.10A', u'Calvert Island beach sand', u'BLANK.2A.10A',
u'0', u'unclassified metagenome', 'blank control', 408169, 0,
'BLANK.2A.10A', u'y', 193.0, u'ENVO:aquatic biome', u'ENVO:water',
u'ENVO:sterile water', 32.84, -117.26, u'1/15/15 0:00', u'GAZ:United States
of America', u'La Jolla, CA', True, 'BLANK.2A.10A', True, u'y', True,
u'complete', u'UCSDMI', u'unknown', u'nan', u'unknown', u'nan', u'nan',
u'nan', u'nan', u'pH meter', u'nan', u'20g dry sand + 20ml dH2O, shake, let
sit ~30mins; pH meter', u'nan', u'refractrometer', u'nan', u'ppt', u'20g
dry sand + 20ml dH2O, shake, let sit ~30mins; conductivity meter', u'nan',
u'gH2O/gsand', u'dry at 110degC', u'nan', u'nan', u'nan', u'nan', u'nan',
u'nan', u'shake sand through sieves', u'nan', u'mg/kg', u'2N KCl
Extractable', u'nan', u'mg/kg', u'2N KCl Extractable', u'nan', u'mg per
kg', u'Bray P-1', u'nan', u'LOI at 450 degC', u'nan', u'ug/g sand or ug/L',
u'91 percent acetone extraction', u'nan', u'unknown', True, True)
Error: invalid input syntax for integer: "nan"
LINE 2: ...true, 'y', true, 'complete', 'UCSDMI', 'unknown', 'nan', 'un...
```

**Comment by antgonza** [comment] 2015-06-01 22:11
Could you try NaN?

**Comment by josenavas** [comment] 2015-06-01 22:16
This is a known error (see https://github.com/biocore/qiita/issues/1173). The problem is that pandas uses a NaN to add an unknown value, but psycopg2 is expecting a None value (so it can represent a NULL). This requires changes to the insertion code.

Closing as it is a duplicate of https://github.com/biocore/qiita/issues/1173

**Closed by josenavas** 2015-06-01 22:16 UTC
Labels: bug

**Comment by ElDeveloper** [comment] 2015-06-01 22:21
Got it, thanks!
