### ISSUE TITLE
Cannot delete study: The object with ID '11426' does not exists in table 'SampleTemplate'

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2331] opened 2017-10-11 03:04 UTC
Steps to reproduce:
Study 11426
Go to Study Description and try to delete the study.
Enter the study name exactly.
Get this error: Error (log id: 152656): The object with ID '11426' does not exists in table 'SampleTemplate'
![Uploading image.png…]()

**Comment by antgonza** [comment] 2017-10-11 03:07
I guess you clicked before the image could be uploaded. Anyway, this is a good catch, the issue is that the study doesn't have a SampleTemplate, we should check before trying to delete.

**Comment by antgonza** [comment] 2017-10-11 23:06
fixed via: https://github.com/biocore/qiita/pull/2339

**Closed by antgonza** 2017-10-11 23:06 UTC
Labels: bug, GUI, must-have
