### ISSUE TITLE
When study completes pre-processing there is no longer an option to reprocess

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1240] opened 2015-06-04 22:37 UTC
If I preprocess a study and it is successful but the sequence counts are very low, I cannot reprocess and select reverse complement barcodes.  I have to reload the prep-template re-link the sequence files and start all over (This happened in study 10178

**Comment by antgonza** [comment] 2015-06-04 22:39
This is a duplicate of https://github.com/biocore/qiita/issues/1026. Note that you can erase the preprocess data and this will allow you to redo ...

**Comment by ackermag** [comment] 2015-06-04 22:44
I tried that and there is still no option to reprocess the original.  Status=success

![screen shot 2015-06-04 at 3 43 47 pm](https://cloud.githubusercontent.com/assets/2014592/7995976/93e15f64-0ad0-11e5-8df5-e39fe5f22e10.png)
![screen shot 2015-06-04 at 3 44 04 pm](https://cloud.githubusercontent.com/assets/2014592/7995975/93dfd7b6-0ad0-11e5-933b-c3d623eece95.png)

**Comment by antgonza** [comment] 2015-06-04 22:47
Yup, this is a new issue generated in the last changes of the GUI.

**Comment by josenavas** [comment] 2015-06-05 00:56
Actually, this is not a problem with the GUI. Is a problem with the process data delete. I don't know if we should spend a lot of time trying to figure out how to solve the delete, or just wait until all this information is in moi so we can drop that column....

**Comment by antgonza** [comment] 2015-06-05 22:59
I think https://github.com/biocore/qiita/pull/1247 is the solution for this ...

**Comment by josenavas** [comment] 2015-06-05 23:14
and probably you're correct hahaha oops

**Comment by ElDeveloper** [comment] 2015-06-05 23:23
> I think #1247 is the solution for this ...

I'm still seeing this issue though :confused:

**Comment by antgonza** [comment] 2015-06-10 17:30
Just figure out why this is happening and will issue a PR to solve it. I think is important to fix as is blocking or making more difficult to work with qiita.

**Closed** 2015-06-11 00:16 UTC
Labels: bug, easy-fix
