### ISSUE TITLE
Feature Request: Separate files stored from files uploaded

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2110] opened 2017-04-19 15:07 UTC
In order to see which files have been uploaded into Qiita, users must go to the upload files page and infer that the text below the grey drag box shows which files have been uploaded into the study. At minimum these files should have a heading, and ideally they would be displayed on a separate page. The separate page should also show links to sample information and sample prep files that have been uploaded and converted so users can track what they have accomplished.

**Comment by antgonza** [comment] 2017-04-19 15:20
I'm not sure I follow this suggestion, could you give more background?

I'm getting confused cause once you add a prep info file, it will be shown below the main buttons (A), which you can click and then see which files you have linked to that prep and the resulting processing files/qiita-artifacts (B).
![screen shot 2017-04-19 at 9 18 09 am](https://cloud.githubusercontent.com/assets/2014559/25187841/6bdedf78-24e1-11e7-9f8a-e8f4434ea4f1.png)

**Comment by adswafford** [comment] 2017-04-24 21:38
Sorry for the lack of details on the feature request. The core of the issue is that novice Qiita users are easily confused by Qiita's handling of files and make mistakes when first learning how to use the system.

Current observed issue:
1) User creates study
2) User clicks on Upload Files button
3) User drags and drops sample information, prep information, and fastq files
4) User clicks on Sample Information, selects their file from the dropdown and clicks Create button
5) User clicks Add New Preparation button, selects file assigns data type and clicks Create New Preparation button
6) User receives red banner telling them they have duplicated columns in their prep information and sample information sheets
7) User wonders what files they uploaded that have the problematic columns and observes there is no page indicating which files have been uploaded
8) User returns to Upload Files page hoping to learn which files did not work, but they are not listed, only the fastq files
9) User uploads sample information and prep information again
10) User repeats steps 4-7 and gets frustrated

Suggested behaviors:
1) Files do not "disappear" when they are processed; if the file must/should be removed, evidence of the original file name should be displayed somewhere to help users troubleshoot
2) If a separate page that shows which files the Qiita study knows about is not made, then at a minimum on the Upload Files page, there should be a heading stating what the files are below the grey dropbox (screenshot attached)
<img width="1415" alt="screen shot 2017-04-24 at 2 13 38 pm" src="https://cloud.githubusercontent.com/assets/27017606/25359846/96f3edde-28fb-11e7-829f-626f9bdba58a.png">

3) If there is opposition to the separate "Uploaded Files" page, then maybe just a page with a log of what was done before the prep information addition step would be helpful. This page could also log when sample information or prep information is updated

**Comment by antgonza** [comment] 2017-04-29 15:34
Thanks for the clarification and suggestions. 

A few things to consider: (1) we decided to remove the "successfully" (warnings aren't consider failure) processed info file to avoid left over files that have been already added, (2) note that based on 1, we don't remove the files that failed, (3) we don't allow download of files that are not linked because we want to avoid users using the system as a simple Dropbox server, and (4) if the file was processed successfully it can be downloaded from the sample or prep info file, thus, recovering their original file.

Now, for your suggestions:
1-3. We could add the original name of the file uploaded to the DB and display it in the sample/prep, the problem is when you update the info. I guess we can only show the latest used or have the history of all of them. The latter option might become a GUI problem.
2. The heading is an easier solution, we can add without much problem.

What do you think?

**Comment by antgonza** [comment] 2017-08-01 15:41
@adswafford, what do you think?

**Comment by adswafford** [comment] 2017-10-11 03:26
It looks like 1-3 is somewhat addressed by the fix #2214 (#2327).

The concern about the dropbox-ing is valid, but can we make it so only admin accounts can download the uploaded files? The situation arises when I'm helping a user in a workshop, via email, or managing the help account where I wind up having to have them email or dropbox me files that I can already see but can't download to troubleshoot b/c they're invalid.

Let's add the header too.

**Comment by antgonza** [comment] 2017-11-28 23:45
Closed by https://github.com/biocore/qiita/pull/2403

**Closed by antgonza** 2017-11-28 23:45 UTC
Labels: CMI-request, CMI-workshop, enhancement, GUI, must-have
