### ISSUE TITLE
Create a gold standard portal

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1391] opened 2015-07-23 00:24 UTC
This portal will have a list (see proposed studies below) of studies that are commonly useful for meta-analyses and that have metadata that has gone **extensive** care:
#### Human associated:
- [ ] Costello
- [ ] Hmp
- [x] American gut
- [ ] Moving pictures
- [ ] Yatusnenko - global gut
- [ ] Mueggue et al - mammals and humans
- [ ] PNAS map paper
- [ ] Fierer keyboard?
- [ ] Infant time series
- [x] RISK
- [x] Janet's twins IBD
- [x] Goodrich UK twins
- [x] Family study
- [x] Bello babies
- [x] Uncontacted yanomami
- [x] Pregnant woman finland
- [ ] Malawi twins
#### Soil
- [ ] Jack's merlot microbiome project
- [ ] Janet's alaskan
- [x] Lauber 88 soils
- [ ] Shenzen samples 1521
#### Built Environment
- [ ] House forensics
- [ ] 40 homes fierer's study
- [ ] Restroom surface biogeography

---

While this list is subject to change and we certainly may be missing a few studies here, we should consider this a starting point.

**Comment by antgonza** [comment] 2015-08-18 10:55
Will these be portals or simply a meta-analysis predefined selection? For the former the user will need to upload their study in the given portal and will be limited to only that portal and for the latter you could have a button that says select samples from predefined selection and those studies/samples will be selected. I like the latter more but I might be missing something.

**Comment by ackermag** [comment] 2015-08-18 12:22
I like the idea of  the second option as Antonio says.  I think we could
add additional studies from the EMP for other environmental packages so it
is more comprehensive and includes other host-associated studies, fresh
water, marine samples etc.
Clearly having studies that are from well-known publications (like HMP) is
important, as well as including studies across platforms - 454 and Illumina.

On Tue, Aug 18, 2015 at 3:55 AM, Antonio Gonzalez <notifications@github.com>
wrote:

> Will these be portals or simply a meta-analysis predefined selection? For
> the former the user will need to upload their study in the given portal and
> will be limited to only that portal and for the latter you could have a
> button that says select samples from predefined selection and those
> studies/samples will be selected. I like the latter more but I might be
> missing something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1391#issuecomment-132171186>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by rob-knight** [comment] 2015-08-18 15:41
I think it needs to be a portal because people will want to do their own meta-analysis from this subset? Or I suppose we could do what they do in GNPS where it’s an attribute of a dataset and you can filter?

**Comment by antgonza** [comment] 2015-08-18 16:42
Just to be clear, a portal is a "virtual" space where users can create/manage/etc their study but is limited to the studies that are in that portal.

Now, my idea was to add a new feature where you have a list of environments (human, built environment, etc) and each one has a predefined list of studies (admin managed, similar to a portal). The the user will simply click on that link (all those samples will get added to their metaanalysis) and they can add their own or other studies, including from other environments ...

**Comment by ackermag** [comment] 2016-04-13 17:48
here is the gold standard discussion - we will need to add some in

**Comment by antgonza** [comment] 2017-01-29 03:18
Resolution: a better solution might be to create a "tagging" system where we can add labels to studies. The first tag will be Gold and selecting this will filter studies to just show you the ones that have it. I though a button "Show me the gold!!!", will be appropriate.

Note that this now became a duplicate of: https://github.com/biocore/qiita/issues/969, closing.

**Closed by antgonza** 2017-01-29 03:18 UTC
Labels: priority: high, qiita.microbio.me
