### ISSUE TITLE
Strange behavior on upload of sample template

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1457] opened 2015-08-27 22:13 UTC
I was attempting to update a sample template in qiita study 10280 - the update worked fine for existing columns but the add samples/columns first gave me an error indicating "has_physical_specimen field has incorrect values, not Bool".  This was incorrect (I had entered TRUE for all samples).  Then I got another error when I tried again and it appears despite the error the new columns have been added but one column that should be integer (host_taxid) had a float rather than an integer which would cause a failure on EBI submission: 10090.0 instead of 10090.  Yoshiki and I checked and my templates are fine (no Excel funny business).  This is the error:

```
ERROR:
No new samples or new columns found in the template. If you want to update existing values, you should use the 'update' functionality.
TRACE:
Traceback (most recent call last):

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1144, in _when_complete
if result.result() is not None:

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/concurrent.py", line 129, in result
raise_exc_info(self.__exc_info)

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/gen.py", line 221, in wrapper
runner.run()

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/gen.py", line 505, in run
yielded = self.gen.throw(*exc_info)

File "/home/qiita/qiita_main/qiita_pet/handlers/study_handlers/description_handlers.py", line 938, in post
study, user)

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/gen.py", line 533, in run
self.yield_point.start(self)

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/gen.py", line 371, in start
self.func(*self.args, **self.kwargs)

File "/home/qiita/qiita_main/qiita_core/util.py", line 95, in wrapper
return func(*args, **kwargs)

File "/home/qiita/qiita_main/qiita_pet/handlers/study_handlers/description_handlers.py", line 325, in add_to_sample_template
self._extend_sample_template(study.sample_template, fp_rsp)

File "/home/qiita/qiita_main/qiita_core/util.py", line 95, in wrapper
return func(*args, **kwargs)

File "/home/qiita/qiita_main/qiita_pet/handlers/study_handlers/description_handlers.py", line 679, in _extend_sample_template
SampleTemplate(st_id).extend(load_template_to_dataframe(fp_rpt))

File "/home/qiita/qiita_main/qiita_db/metadata_template/sample_template.py", line 241, in extend
self._common_extend_steps(md_template)

File "/home/qiita/qiita_main/qiita_db/metadata_template/base_metadata_template.py", line 664, in _common_extend_steps
"No new samples or new columns found in the template. "

QiitaDBError: No new samples or new columns found in the template. If you want to update existing values, you should use the 'update' functionality.
```

**Comment by ElDeveloper** [comment] 2015-08-27 22:19
BTW, I tried parsing the file that @ackermag uploaded (using
load_template_to_dataframe) and the `host_taxid` column was an integer,
this leads me to believe that there may be something funky going on with
the update operation (though this is just a guess).

**Comment by josenavas** [comment] 2015-08-27 22:35
The error points that the are no new columns/samples. Which is the actual error returned when doing the update with the exact same template?

BTW, there was a bug on the new update code, but I'm unsure if it is related with this. I fixed it in my last PR. We can deploy on sunday and see if that fixes the error.

**Comment by ElDeveloper** [comment] 2015-08-27 23:07
Right, that is the error as it stands. However when the template was
initially uploaded it raised an error regarding one of the columns not
being a boolean, so after the file was checked/corrected the error
above was displayed and in addition a column host_taxid had just been
converted into a float (likely due to a pandas operation). Does that
make sense? @ackermag may be able to give you more descriptive
explanation.

**Comment by josenavas** [comment] 2015-08-28 20:49
I took a look at this. The current error displayed when you try to update is the error that I found in my PR. The problem with the wrong datatypes my guess is that it is because the column changed type (probably as a result of a previous typo). I'm unable to reproduce the error in my machine as the datatype for host_taxid is detected correctly. As a solution, I will update te data types manually in the DB on sunday, when I update the system, and we will be keeping a close eye on this to check if that happens again.

**Comment by ElDeveloper** [comment] 2015-08-28 21:42
Thanks!

**Comment by antgonza** [comment] 2015-10-10 18:30
@josenavas can we close this?

**Comment by ackermag** [comment] 2015-10-10 20:04
Have not noticed this behavior again.

On Sat, Oct 10, 2015 at 11:30 AM, Antonio Gonzalez <notifications@github.com
> wrote:

> @josenavas <https://github.com/josenavas> can we close this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1457#issuecomment-147114797>.
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by josenavas** [comment] 2015-10-10 21:45
Yup, I clean the database manually.

**Closed by josenavas** 2015-10-10 21:45 UTC
