### ISSUE TITLE
Updated user contact info is not reflected in Lab Contact drop down menu when creating a new study

### ISSUE THREAD

**Issue by mestaki** [biocore/qiita#3027] opened 2020-08-28 01:21 UTC
I created my user profile while at institution X, later on updated my profile to say institute Y. However, when creating a new study, the drop down menu under "Lab Contact" still only shows contact info as institution X.
Looks to me that perhaps the drop-down menu list doesn't get proper updates?

**Comment by antgonza** [comment] 2020-09-02 18:35
This is correct, the issue is that those 2 are actually 2 different entries and there is no way to modify the lab contact information (except add a new one). The main description of this issue can be found here: https://github.com/biocore/qiita/issues/304. Closing as duplicate.

**Closed by antgonza** 2020-09-02 18:35 UTC
