### ISSUE TITLE
Artifacts on study list page do not match study

### ISSUE THREAD

**Issue by shaekin** [biocore/qiita#2635] opened 2018-07-27 18:14 UTC
When I expand the options for Suzie Hong's study, Qiita ID 11259, it shows some ITS files that are not in the file tree.  

Here's an image of the expanded files:
![image](https://user-images.githubusercontent.com/31516412/43339237-a66728b6-918d-11e8-8f2e-191057ac92d9.png)

Here's the file tree:
![image](https://user-images.githubusercontent.com/31516412/43339411-1d5dede2-918e-11e8-9708-7568c23e4d49.png)

I'm not sure what's causing the files to show up one place but not the other.  Thank you!

**Comment by antgonza** [comment] 2018-07-27 18:16
The list you are showing is the list of all BIOMs for all preparations in your study and the three visualization is for a single prep. Hope this helps and if it does, can you close this issue? Thanks!

**Comment by antgonza** [comment] 2018-08-13 13:47
Clarifying this issue, the problem is that the user only has access to 1 prep and it's seeing the artifacts for all preps.

**Comment by shaekin** [comment] 2018-08-13 18:44
I do only have one prep available on Qiita.  Here's a screen shot of that if it's helpful:
![image](https://user-images.githubusercontent.com/31516412/44051286-4a538d94-9eee-11e8-9729-4e6083b0f595.png)

**Closed** 2018-09-21 13:37 UTC
