### ISSUE TITLE
Need a way to add all biom files from study at once

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2209] opened 2017-08-09 16:16 UTC
There should be a button that lets users add all bioms, and all bioms of the same type (16S closed ref vs deblur with Trim100, etc.) at the top of studies instead of making users click each button.

**Comment by antgonza** [comment] 2017-08-18 12:03
We need to figure out what's the easiest way to do this and if worth it. In the past we had this option and users weren't aware that you could add just one so I would suggest making this an option within the list of artifacts and not a super button on the top, like it just to be. Now, the problem is that in reality it only makes sense to add all artifacts that are processed the same way - same so we should be smart on how to display and add this feature. Additionally, note that users will only really should do this when they have multiple preps in the list, which we could also make optional (only show when we have this situation).

**Comment by antgonza** [comment] 2017-10-04 17:19
The decision is to add another level in the study list per study, the next level will have a list of the available processing parameters (you should be able to add all in a single click) and then each of them will have all the artifacts.

**Comment by antgonza** [comment] 2017-10-11 23:07
fixed via: https://github.com/biocore/qiita/pull/2329

**Closed by antgonza** 2017-10-11 23:07 UTC
Labels: CMI-workshop, enhancement, GUI, must-have
