### ISSUE TITLE
Users should be able to directly add the biom file to an analysis from the processing network view

### ISSUE THREAD

**Issue by adswafford** [biocore/qiita#2232] opened 2017-08-11 03:52 UTC
I would suggest a button on the page and a right-click event if possible:
http://visjs.org/examples/network/events/interactionEvents.html

**Comment by antgonza** [comment] 2017-09-21 12:00
This is basically a duplicate of #858 so it's not solved.

**Closed by antgonza** 2017-09-21 12:00 UTC
Labels: CMI-workshops, enhancement, GUI
