### ISSUE TITLE
analysis will fail if the pi name has not valid characters  

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#2768] opened 2018-12-20 14:27 UTC
The error is: ```There are invalid (non UTF-8) characters in your information file. The offending fields and their location (row, column) are listed below, invalid characters are represented using 🐾: "XXXX🐾🐾XXXX" = (1, 45), (1, 46)```, where the X are the OK chars but replacing them for privacy.```

The fix is either to not allow special characters in the name of the PI or escape them during insertion into the metadata (I like the latter).

**Comment by charles-cowart** [comment] 2018-12-20 21:35
Confirmed the following files (that appear to be associated with study 12103 appear to be fine, and without the characters that would cause the above error message to appear:
12103_20181118-162124.txt 
12103_prep_5756_20181118-162124.txt
12103_prep_5756_qiime_20181118-162124.txt

**Comment by charles-cowart** [comment] 2018-12-20 22:36
I'd rather take it out at the GUI level for now, just to remain consistent with the other things we've done. I think once Qiita moves over to Python3, and can handle unicode natively, I think it would be better to allow unicode characters in all fields. We would just need to sanitize data going into things like Qiime, which may not support Unicode. Our PostgreSQL instance looks like it's already set up to support unicode. We'd just need to audit Qiita.

**Comment by antgonza** [comment] 2018-12-20 22:40
AFAIK, those restrictions are due to Qiime1 but I might be wrong and we _might_ be able to remove them; however, we will need to test it ...

**Comment by charles-cowart** [comment] 2019-01-23 19:11
Closing, as part of most recent release.

**Closed by charles-cowart** 2019-01-23 19:11 UTC
Labels: metanalysis
