### ISSUE TITLE
trying to upload sample template generates this message

### ISSUE THREAD

**Issue by ackermag** [biocore/qiita#1147] opened 2015-05-04 15:40 UTC
Some columns required to generate a QIIME-compliant mapping file are not present in the template. A placeholder value (XXQIITAXX) has been used to populate these columns. Missing columns: LinkerPrimerSequence, BarcodeSequence

LinkerPrimerSequence and Barcode Sequence are mapping file specific not sample_template

**Comment by josenavas** [comment] 2015-05-04 15:42
@ackermag If the sample template has already a prep template associated, it re-generates the QIIME-mapping file, because the sample template information is also included there. Closing as this is not a bug.

**Comment by squirrelo** [comment] 2015-05-04 16:27
This is a bug that needs to get fixed. It is confusing to users that uploading a sample template complains about prep template columns and vice versa. We need a way to show the corresponding info for the correct templates only.

**Comment by josenavas** [comment] 2015-05-04 17:49
Chatted with @ackermag 

Note that this is happening as a result of a previous bug; and again, this is not a bug.
What is happening is that when the sample template is updated, the QIIME mapping files are re-generated. This is done to keep the files and the DB consistent.

The solution is to let the user know that the QIIME mapping files will be re-generated, but we cannot suppress those warnings.

**Comment by antgonza** [comment] 2015-06-12 13:47
@josenavas and @squirrelo I think this can be closed, right?

**Closed** 2015-06-12 16:51 UTC
Labels: GUI
