### ISSUE TITLE
Lookup table for *_status and user level

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#410] opened 2014-10-15 15:25 UTC
This field currently takes a varchar with the unenforced vocabulary: `('not submitted', 'submitting', 'success', 'failed')`

**Comment by antgonza** [comment] 2015-10-12 01:17
Even so that I can see why it will be nice to have a lookup table, I believe the current way is nice as it allows us to store the failure in the text so we can display to the user. However, I don't have strong feelings about it as long as we can do the same with the new implementation. 

What do you guys think?

**Comment by josenavas** [comment] 2015-10-12 01:20
In order to have a lookup table for this we need a normalized way of storing the errors across the system (i.e. using the Log table). Probably will be easier to do after the artifact changes. My vote goes to move this to alpha 0.4

**Comment by antgonza** [comment] 2017-08-03 20:24
This is basically a duplicate of https://github.com/biocore/qiita/issues/292 but here he have more info. Additionally, note that we would need to do the same for **the user level status**

**Comment by antgonza** [comment] 2019-12-13 22:57
AFAIK, this can be closed.

**Closed by antgonza** 2019-12-13 22:57 UTC
Labels: database changes, priority: low
