### ISSUE TITLE
Name in the qiita_user can break study list

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1308] opened 2015-06-29 13:18 UTC
If a name in the qiita_user has a ø (for example) it will break the study list silently.

**Comment by josenavas** [comment] 2015-08-07 20:16
@antgonza 
I'm unable to reproduce this error. This is the contents in the DB for a test user:
```
SELECT name FROM qiita.qiita_user WHERE email = 'test@foo.bar';
 name  
-------
 testø
(1 row)
```

And I have no trouble showing the listing page with that user:
![screen shot 2015-08-07 at 1 14 00 pm](https://cloud.githubusercontent.com/assets/2501478/9145051/35e8ad28-3d06-11e5-8f05-0ed7b9e84d9a.png)

Or any other user, and even sharing another study with him:
![screen shot 2015-08-07 at 1 14 56 pm](https://cloud.githubusercontent.com/assets/2501478/9145071/54960a68-3d06-11e5-81f1-f3b379a68570.png)

Can you provide more information about the error and how to duplicate it?

**Comment by antgonza** [comment] 2015-08-07 20:26
Qiita user not study title.

**Comment by josenavas** [comment] 2015-08-07 20:45
Do you mean the user name or the user email? In my previous comment, look at the contents of the user information:

```
SELECT name FROM qiita.qiita_user WHERE email = 'test@foo.bar';
 name  
-------
 testø
(1 row)
```

**Comment by antgonza** [comment] 2015-08-07 20:53
Just tested and you are right, this is working fine now.

**Comment by josenavas** [comment] 2015-08-07 21:00
Weird... issues magically solved... probably it was related with something else... should we close the issue?

**Comment by antgonza** [comment] 2015-08-07 21:01
:+1:

**Closed** 2015-08-07 21:02 UTC
Labels: bug
